version: "3.9"

services:
  pagopa-ecommerce-transactions:
    container_name: pagopa-ecommerce-transactions
    build:
      context: .
    ports:
      - "8080:8080"
    networks:
      - pagopa-ecommerce-net
    env_file: .env

  pagopa-ecommerce-sessions-service:
    container_name: pagopa-ecommerce-sessions-service
    build:
      context: .
      dockerfile: Dockerfile.sessions-service
    ports:
        - "8082:8080"
    networks:
      - pagopa-ecommerce-net
    env_file: .env

  pagopa-ecommerce-payment-instruments-service:
    container_name: pagopa-ecommerce-payment-instruments-service
    build:
      context: .
      dockerfile: Dockerfile.payment-instruments
    ports:
      - "8083:8080"
    networks:
      - pagopa-ecommerce-net
    env_file: .env

  pagopa-node-mock:
    container_name: pagopa-node-mock
    build:
      context: .
      dockerfile: Dockerfile.nodo-mock
    environment:
      PORT: 3002
      PAGOPA_PROXY_PORT: 3000
      PAGOPA_PROXY_HOST: http://pagopaproxy
      PAGOPA_NODO_HOST: http://pagopa-node-mock
      PAGOPA_ID_CANALE: 97735020584_02
      PAGOPA_ID_CANALE_PAGAMENTO: 97735020584_xx
      PAGOPA_ID_INT_PSP: 97735020584
      PAGOPA_ID_PSP: PAGOPA_01
      PAGOPA_NODO_PASSWORD: password
    ports:
        - "3002:3002"
    networks:
      - pagopa-ecommerce-net

  redis:
    container_name: pagopa-ecommerce-redis
    image: redis
    command: ["sh", "-c", 'exec redis-server --requirepass "$$REDIS_PASSWORD"']
    ports:
      - "6379:6379"
    networks:
      - pagopa-ecommerce-net

  redis-insight:
    image: redislabs/redisinsight
    ports:
      - "8001:8001"
    networks:
      - pagopa-ecommerce-net

  mongo:
    container_name: pagopa-ecommerce-mongo
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_PASSWORD
    networks:
      - pagopa-ecommerce-net
    healthcheck:
      test: echo "db.stats().ok" | mongo --quiet
      interval: 10s

  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    networks:
      - pagopa-ecommerce-net
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: $MONGO_USERNAME
      ME_CONFIG_MONGODB_ADMINPASSWORD: $MONGO_PASSWORD
      ME_CONFIG_MONGODB_URL: mongodb://$MONGO_USERNAME:$MONGO_PASSWORD@pagopa-ecommerce-mongo:27017/
    depends_on:
      mongo:
        condition: service_healthy

  pagopa-api-config-mock:
    build:
      context: .
      dockerfile: Dockerfile.api-config-mock
    container_name: pagopa-api-config-mock
    ports:
      - "8084:3000"
    networks:
      - pagopa-ecommerce-net

networks:
  pagopa-ecommerce-net:
    name: pagopa-ecommerce-net
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450
