version: "3.9"

services:
  pagopa-ecommerce-transactions:
    build:
      context: .
    ports:
      - "8080:8080"
    networks:
      - pagopa-ecommerce
    env_file: .env

  redis:
    image: redis
    command: ["sh", "-c", 'exec redis-server --requirepass "$$REDIS_PASSWORD"']
    ports:
      - "6379:6379"
    networks:
      - pagopa-ecommerce

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_PASSWORD
    networks:
      - pagopa-ecommerce
    healthcheck:
      test: echo "db.stats().ok" | mongo --quiet
      interval: 10s

  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    networks:
      - pagopa-ecommerce
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: $MONGO_USERNAME
      ME_CONFIG_MONGODB_ADMINPASSWORD: $MONGO_PASSWORD
      ME_CONFIG_MONGODB_URL: mongodb://$MONGO_USERNAME:$MONGO_PASSWORD@mongo:27017/
    depends_on:
      mongo:
        condition: service_healthy

networks:
  pagopa-ecommerce:
    name: pagopa-ecommerce
