version: "3.9"

services:
  pagopa-ecommerce-transactions:
    build:
      context: .
    networks:
      - pagopa-ecommerce

  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_PASSWORD
    networks:
      - pagopa-ecommerce

  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    networks:
      - pagopa-ecommerce
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: $MONGO_USERNAME
      ME_CONFIG_MONGODB_ADMINPASSWORD: $MONGO_PASSWORD
      ME_CONFIG_MONGODB_URL: mongodb://$MONGO_USERNAME:$MONGO_PASSWORD@mongo:27017/

networks:
  pagopa-ecommerce:
    name: pagopa-ecommerce
