openapi: 3.0.0
info:
  version: 0.1.0
  title: Pagopa eCommerce payment transactions service
  description: This microservice that handles transactions' lifecycle and workflow.
paths:
  /transactions:
    post:
      operationId: newTransaction
      summary: Make a new transaction
      requestBody:
        $ref: "#/components/requestBodies/NewTransactionRequest"
      responses:
        '200':
          description: New transaction successfully created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NewTransactionResponse'
components:
  schemas:
    RptId:
      type: string
      pattern: '([a-zA-Z\d]{1,35})|(RF\d{2}[a-zA-Z\d]{1,21})'
    Iban:
      type: string
      pattern: '[a-zA-Z]{2}[0-9]{2}[a-zA-Z0-9]{1,30}'
    NewTransactionRequest:
      type: object
      description: Request body for creating a new transaction
      properties:
        rptId:
          $ref: '#/components/schemas/RptId'
      required:
        - rptId
      example:
        rptId: string
    NewTransactionResponse:
      type: object
      description: Transaction data returned when creating a new transaction
      properties:
        amount:
          $ref: '#/components/schemas/AmountEuroCents'
        recipientIban:
          $ref: '#/components/schemas/Iban'
        reason:
          type: string
          minLength: 1
          maxLength: 140
        beneficiary:
          $ref: '#/components/schemas/Beneficiary'
        installments:
          $ref: '#/components/schemas/PaymentInstallments'
      required:
        - amount
      example:
        amount: 200
    AmountEuroCents:
      description: Amount for payments, in euro cents
      type: integer
      minimum: 0
      maximum: 99999999
    Beneficiary:
      description: Beneficiary institution related to a payment
      type: object
      properties:
        beneficiaryId:
          type: string
          minLength: 1
          maxLength: 35
        denominazioneBeneficiario:
          type: string
          minLength: 1
          maxLength: 70
        codiceUnitOperBeneficiario:
          type: string
          minLength: 1
          maxLength: 35
        denomUnitOperBeneficiario:
          type: string
          minLength: 1
          maxLength: 70
        address:
          type: string
          minLength: 1
          maxLength: 70
        streetNumber:
          type: string
          minLength: 1
          maxLength: 16
        postalCode:
          type: string
          minLength: 1
          maxLength: 16
        city:
          type: string
          minLength: 1
          maxLength: 35
        province:
          type: string
          minLength: 1
          maxLength: 35
        country:
          type: string
          pattern: '[A-Z]{2}'
      required:
        - beneficiaryId
        - denominazioneBeneficiario
    PaymentInstallments:
      description: Payment installments (optional)
      type: array
      items:
        $ref: '#/components/schemas/Installment'
    Installment:
      description: Payment installment
      type: object
      properties:
        installment:
          type: string
          minLength: 1
          maxLength: 35
        data:
          $ref: '#/components/schemas/InstallmentDetails'
    InstallmentDetails:
      description: Amount and reason related to a payment installment
      type: object
      properties:
        reason:
          type: string
          minLength: 1
          maxLength: 25
        amount:
          $ref: '#/components/schemas/AmountEuroCents'
  requestBodies:
    NewTransactionRequest:
      required: true
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/NewTransactionRequest"
