apiVersion: v2
name: pagopa-ecommerce-transactions-service
description: Microservice that handles transactions lifecycle and workflow in ecommerce pagoPA
type: application
version: 1.38.1
appVersion: 1.38.1
dependencies:
  - name: microservice-chart
    version: 2.8.0
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
