apiVersion: v2
name: pagopa-ecommerce-transactions-service
description: Microservice that handles transactions lifecycle and workflow in ecommerce pagoPA
type: application
version: 0.4.25
appVersion: 0.4.25
dependencies:
  - name: microservice-chart
    version: 1.21.0
    repository: "https://pagopa.github.io/aks-microservice-chart-blueprint"
