microservice-chart:
  namespace: "ecommerce"
  nameOverride: ""
  fullnameOverride: ""
  image:
    repository: pagopadcommonacr.azurecr.io/pagopaecommercetransactionsservice
    tag: "0.19.11" #improve
    pullPolicy: Always
  livenessProbe:
    httpGet:
      path: /actuator/health/liveness
      port: 8080
    initialDelaySeconds: 60
    failureThreshold: 6
    periodSeconds: 10
  readinessProbe:
    httpGet:
      path: /actuator/health/readiness
      port: 8080
    initialDelaySeconds: 60
    failureThreshold: 6
    periodSeconds: 10
  deployment:
    create: true
  service:
    create: true
    type: ClusterIP
    ports:
      - 8080
  ingress:
    create: true
    host: "weudev.ecommerce.internal.dev.platform.pagopa.it"
    path: /pagopa-ecommerce-transactions-service/(.*)
    servicePort: 8080
  serviceAccount:
    create: false
    annotations: {}
    name: ""
  podAnnotations: {}
  podSecurityContext:
    seccompProfile:
      type: RuntimeDefault
  securityContext:
    allowPrivilegeEscalation: false
  resources:
    requests:
      memory: "512Mi"
      cpu: "300m"
    limits:
      memory: "512Mi"
      cpu: "300m"
  autoscaling:
    minReplica: 1
    maxReplica: 2
    pollingInterval: 30 # seconds
    cooldownPeriod: 300 # seconds
    triggers:
      - type: azure-monitor
        metadata:
          tenantId: 7788edaf-0346-4068-9d79-c868aed15b3d
          subscriptionId: bbe47ad4-08b3-4925-94c5-1278e5819b86
          resourceGroupName: pagopa-d-ecommerce-sec-rg
          resourceURI: Microsoft.KeyVault/vaults/pagopa-d-ecommerce-kv
          metricName: ServiceApiHit
          # metricNamespace: Microsoft.KeyVault/vaults
          # metricFilter: namespace eq 'default'
          # metricAggregationInterval: "-1:1:0"
          metricAggregationType: Count
          targetValue: "30"
  envConfig:
    MONGO_HOST: pagopa-d-weu-ecommerce-cosmos-account.mongo.cosmos.azure.com
    MONGO_USERNAME: pagopa-d-weu-ecommerce-cosmos-account
    MONGO_PORT: "10255"
    MONGO_SSL_ENABLED: "true"
    REDIS_HOST: pagopa-d-weu-ecommerce-redis.redis.cache.windows.net
    REDIS_PORT: "6380"
    REDIS_SSL_ENABLED: "true"
    NODO_HOSTNAME: https://api.dev.platform.pagopa.it
    NODE_FOR_PSP_URI: /nodo/node-for-psp/v1
    NODO_READ_TIMEOUT: "10000"
    NODO_CONNECTION_TIMEOUT: "10000"
    NODO_PARALLEL_REQUESTS: "5"
    ECOMMERCE_PAYMENT_METHODS_URI: https://api.dev.platform.pagopa.it/ecommerce/payment-methods-service/v1
    ECOMMERCE_PAYMENT_METHODS_READ_TIMEOUT: "10000"
    ECOMMERCE_PAYMENT_METHODS_CONNECTION_TIMEOUT: "10000"
    PAYMENT_TRANSACTIONS_GATEWAY_URI: https://api.dev.platform.pagopa.it/payment-transactions-gateway/internal/v1
    PAYMENT_TRANSACTIONS_GATEWAY_READ_TIMEOUT: "10000"
    PAYMENT_TRANSACTIONS_GATEWAY_CONNECTION_TIMEOUT: "10000"
    NOTIFICATIONS_SERVICE_URI: https://api.dev.platform.pagopa.it/ecommerce/notifications-service/v1
    NOTIFICATIONS_SERVICE_READ_TIMEOUT: "10000"
    NOTIFICATIONS_SERVICE_CONNECTION_TIMEOUT: "10000"
    TRANSACTION_EXPIRATION_QUEUE_NAME: pagopa-d-weu-ecommerce-transactions-expiration-queue
    TRANSACTION_CLOSE_PAYMENT_RETRY_QUEUE_NAME: pagopa-d-weu-ecommerce-transactions-close-payment-retry-queue
    TRANSACTION_CLOSE_PAYMENT_QUEUE_NAME: pagopa-d-weu-ecommerce-transactions-close-payment-queue
    TRANSACTION_REFUND_QUEUE_NAME: pagopa-d-weu-ecommerce-transactions-refund-queue
    TRANSACTION_NOTIFICATIONS_QUEUE_NAME: pagopa-d-weu-ecommerce-transaction-notifications-queue
    PAYMENT_TOKEN_VALIDITY_TIME: "900"
    TRANSACTIONS_RETRY_OFFSET: "60"
    CLOSURE_RETRY_INTERVAL: "30"
    WEB_LOGGING_LEVEL: "off"
    SERVICE_LOGGING_LEVEL: "info"
    JWT_TOKEN_VALIDITY_TIME_MILLIS: "1800000"
    PERSONAL_DATA_VAULT_API_BASE_PATH: "https://api.uat.tokenizer.pdv.pagopa.it/tokenizer/v1"
    WARMUP_REQUEST_NEW_TRANSACTION_NOTICE_CODE_PREFIX: "3111"
    LOGO_CARD_BRANDING_MAPPING: >
      { VISA:'https://dev.checkout.pagopa.it/assets/creditcard/carta_visa.png',  MASTERCARD:'https://dev.checkout.pagopa.it/assets/creditcard/carta_mc.png', DINERS:'https://dev.checkout.pagopa.it/assets/creditcard/carta_diners.png', MAESTRO:'https://dev.checkout.pagopa.it/assets/creditcard/carta_maestro.png', AMEX:'https://dev.checkout.pagopa.it/assets/creditcard/carta_amex.png', UNKNOWN:'https://dev.checkout.pagopa.it/assets/creditcard/generic.png' }

    ELASTIC_APM_SERVICE_NAME: pagopa-ecommerce-transactions-service
    ELASTIC_APM_APPLICATION_PACKAGES: it.pagopa.ecommerce.transactions
    ELASTIC_APM_SERVER_URL: http://quickstart-apm-http.elastic-system.svc:8200
    ELASTIC_APM_LOG_SENDING: 'true'
  envSecret:
    MONGO_PASSWORD: mongo-ecommerce-password
    REDIS_PASSWORD: redis-ecommerce-password
    NODO_CONNECTION_STRING: nodo-connection-string
    NOTIFICATIONS_SERVICE_API_KEY: notifications-service-api-key
    ECOMMERCE_STORAGE_CONNECTION_STRING: ecommerce-storage-connection-string
    PAYMENT_TRANSACTIONS_GATEWAY_API_KEY: payment-transactions-gateway-api-key
    JWT_SECRET: sessions-jwt-secret
    PERSONAL_DATA_VAULT_API_KEY: personal-data-vault-api-key
    ELASTIC_APM_SECRET_TOKEN: elastic-apm-secret-token
    ECOMMERCE_PAYMENT_METHODS_APY_KEY: payment-method-api-key
  keyvault:
    name: "pagopa-d-ecommerce-kv"
    tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"
  nodeSelector: {}
  tolerations: []
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node_type
                operator: In
                values:
                  - user
  canaryDelivery:
    deployment:
      image:
        tag: ""
