microservice-chart:
  namespace: "ecommerce"
  nameOverride: ""
  fullnameOverride: ""
  canaryDelivery:
    create: false
    ingress:
      create: true
      canary:
        type: bluegreen
    service:
      create: true
    deployment:
      create: true
      image:
        repository: pagopapcommonacr.azurecr.io/pagopaecommercetransactionsservice
        tag: "latest"
        pullPolicy: Always
    envConfig:
      MONGO_HOST: pagopa-p-weu-ecommerce-cosmos-account.mongo.cosmos.azure.com
      MONGO_USERNAME: pagopa-p-weu-ecommerce-cosmos-account
      MONGO_PORT: "10255"
      MONGO_SSL_ENABLED: "true"
      REDIS_HOST: pagopa-p-weu-ecommerce-redis.redis.cache.windows.net
      REDIS_PORT: "6380"
      REDIS_SSL_ENABLED: "true"
      NODO_HOSTNAME: https://api.platform.pagopa.it
      NODE_FOR_PSP_URI: /nodo/node-for-psp/v1
      NODO_READ_TIMEOUT: "10000"
      NODO_CONNECTION_TIMEOUT: "10000"
      NODO_PARALLEL_REQUESTS: "5"
      ECOMMERCE_PAYMENT_METHODS_URI: https://api.platform.pagopa.it/ecommerce/payment-methods-service/v1
      ECOMMERCE_PAYMENT_METHODS_READ_TIMEOUT: "10000"
      ECOMMERCE_PAYMENT_METHODS_CONNECTION_TIMEOUT: "10000"
      PAYMENT_TRANSACTIONS_GATEWAY_URI: https://api.platform.pagopa.it/payment-transactions-gateway/internal/v1
      PAYMENT_TRANSACTIONS_GATEWAY_READ_TIMEOUT: "10000"
      PAYMENT_TRANSACTIONS_GATEWAY_CONNECTION_TIMEOUT: "10000"
      NOTIFICATIONS_SERVICE_URI: https://api.platform.pagopa.it/ecommerce/notifications-service/v1
      NOTIFICATIONS_SERVICE_READ_TIMEOUT: "10000"
      NOTIFICATIONS_SERVICE_CONNECTION_TIMEOUT: "10000"
      TRANSACTION_EXPIRATION_QUEUE_NAME: pagopa-p-weu-ecommerce-transactions-expiration-queue
      TRANSACTION_CLOSE_PAYMENT_RETRY_QUEUE_NAME: pagopa-p-weu-ecommerce-transactions-close-payment-retry-queue
      TRANSACTION_CLOSE_PAYMENT_QUEUE_NAME: pagopa-p-weu-ecommerce-transactions-close-payment-queue
      TRANSACTION_REFUND_QUEUE_NAME: pagopa-p-weu-ecommerce-transactions-refund-queue
      TRANSACTION_NOTIFICATIONS_QUEUE_NAME: pagopa-p-weu-ecommerce-transaction-notifications-queue
      PAYMENT_TOKEN_VALIDITY_TIME: "900"
      TRANSACTIONS_RETRY_OFFSET: "60"
      CLOSURE_RETRY_INTERVAL: "30"
      WEB_LOGGING_LEVEL: "off"
      SERVICE_LOGGING_LEVEL: "info"
      JWT_TOKEN_VALIDITY_TIME_MILLIS: "1800000"
      PERSONAL_DATA_VAULT_API_BASE_PATH: "https://api.tokenizer.pdv.pagopa.it/tokenizer/v1"
      WARMUP_REQUEST_NEW_TRANSACTION_NOTICE_CODE_PREFIX: "3020"
      LOGO_CARD_BRANDING_MAPPING: >
        { VISA:'https://checkout.pagopa.it/assets/creditcard/carta_visa.png',  MASTERCARD:'https://checkout.pagopa.it/assets/creditcard/carta_mc.png', DINERS:'https://checkout.pagopa.it/assets/creditcard/carta_diners.png', MAESTRO:'https://checkout.pagopa.it/assets/creditcard/carta_maestro.png', AMEX:'https://checkout.pagopa.it/assets/creditcard/carta_amex.png', UNKNOWN:'https://checkout.pagopa.it/assets/creditcard/generic.png' }

      SERVER_ERROR_INCLUDE_STACKTRACE: "never"
      ELASTIC_APM_SERVICE_NAME: pagopa-ecommerce-transactions-service-blue
      ELASTIC_APM_APPLICATION_PACKAGES: it.pagopa.ecommerce.transactions
      ELASTIC_APM_SERVER_URL: http://quickstart-apm-http.elastic-system.svc:8200
      ELASTIC_APM_LOG_SENDING: "false"
    envSecret:
      MONGO_PASSWORD: mongo-ecommerce-password
      REDIS_PASSWORD: redis-ecommerce-password
      NODO_CONNECTION_STRING: nodo-connection-string
      PAYMENT_TRANSACTIONS_GATEWAY_API_KEY: payment-transactions-gateway-api-key
      JWT_SECRET: sessions-jwt-secret
      PERSONAL_DATA_VAULT_API_KEY: personal-data-vault-api-key
      ELASTIC_APM_SECRET_TOKEN: elastic-apm-secret-token
      ECOMMERCE_PAYMENT_METHODS_APY_KEY: payment-method-api-key
  image:
    repository: pagopapcommonacr.azurecr.io/pagopaecommercetransactionsservice
    tag: "0.19.10"
    pullPolicy: Always
  livenessProbe:
    httpGet:
      path: /actuator/health/liveness
      port: 8080
    initialDelaySeconds: 60
    failureThreshold: 6
    periodSeconds: 10
  readinessProbe:
    httpGet:
      path: /actuator/health/readiness
      port: 8080
    initialDelaySeconds: 60
    failureThreshold: 6
    periodSeconds: 10
  service:
    create: true
    type: ClusterIP
    ports:
      - 8080
  ingress:
    create: true
    host: "weuprod.ecommerce.internal.platform.pagopa.it"
    path: /pagopa-ecommerce-transactions-service/(.*)
    servicePort: 8080
  serviceAccount:
    create: false
    annotations: {}
    name: ""
  podAnnotations: {}
  podSecurityContext:
    seccompProfile:
      type: RuntimeDefault
  securityContext:
    allowPrivilegeEscalation: false
  resources:
    requests:
      memory: "512Mi"
      cpu: "300m"
    limits:
      memory: "512Mi"
      cpu: "500m"
  autoscaling:
    enable: true
    minReplica: 2
    maxReplica: 10
    pollingInterval: 30 # seconds
    cooldownPeriod: 300 # seconds
    triggers:
      - type: cpu
        metadata:
          # Required
          type: Utilization # Allowed types are 'Utilization' or 'AverageValue'
          value: "70"
  envConfig:
    MONGO_HOST: pagopa-p-weu-ecommerce-cosmos-account.mongo.cosmos.azure.com
    MONGO_USERNAME: pagopa-p-weu-ecommerce-cosmos-account
    MONGO_PORT: "10255"
    MONGO_SSL_ENABLED: "true"
    REDIS_HOST: pagopa-p-weu-ecommerce-redis.redis.cache.windows.net
    REDIS_PORT: "6380"
    REDIS_SSL_ENABLED: "true"
    NODO_HOSTNAME: https://api.platform.pagopa.it
    NODE_FOR_PSP_URI: /nodo/node-for-psp/v1
    NODO_READ_TIMEOUT: "10000"
    NODO_CONNECTION_TIMEOUT: "10000"
    NODO_PARALLEL_REQUESTS: "5"
    ECOMMERCE_PAYMENT_METHODS_URI: https://api.platform.pagopa.it/ecommerce/payment-methods-service/v1
    ECOMMERCE_PAYMENT_METHODS_READ_TIMEOUT: "10000"
    ECOMMERCE_PAYMENT_METHODS_CONNECTION_TIMEOUT: "10000"
    PAYMENT_TRANSACTIONS_GATEWAY_URI: https://api.platform.pagopa.it/payment-transactions-gateway/internal/v1
    PAYMENT_TRANSACTIONS_GATEWAY_READ_TIMEOUT: "10000"
    PAYMENT_TRANSACTIONS_GATEWAY_CONNECTION_TIMEOUT: "10000"
    NOTIFICATIONS_SERVICE_URI: https://api.platform.pagopa.it/ecommerce/notifications-service/v1
    NOTIFICATIONS_SERVICE_READ_TIMEOUT: "10000"
    NOTIFICATIONS_SERVICE_CONNECTION_TIMEOUT: "10000"
    TRANSACTION_EXPIRATION_QUEUE_NAME: pagopa-p-weu-ecommerce-transactions-expiration-queue
    TRANSACTION_CLOSE_PAYMENT_RETRY_QUEUE_NAME: pagopa-p-weu-ecommerce-transactions-close-payment-retry-queue
    TRANSACTION_CLOSE_PAYMENT_QUEUE_NAME: pagopa-p-weu-ecommerce-transactions-close-payment-queue
    TRANSACTION_REFUND_QUEUE_NAME: pagopa-p-weu-ecommerce-transactions-refund-queue
    TRANSACTION_NOTIFICATIONS_QUEUE_NAME: pagopa-p-weu-ecommerce-transaction-notifications-queue
    PAYMENT_TOKEN_VALIDITY_TIME: "900"
    TRANSACTIONS_RETRY_OFFSET: "60"
    CLOSURE_RETRY_INTERVAL: "30"
    WEB_LOGGING_LEVEL: "off"
    SERVICE_LOGGING_LEVEL: "info"
    JWT_TOKEN_VALIDITY_TIME_MILLIS: "1800000"
    PERSONAL_DATA_VAULT_API_BASE_PATH: "https://api.tokenizer.pdv.pagopa.it/tokenizer/v1"
    WARMUP_REQUEST_NEW_TRANSACTION_NOTICE_CODE_PREFIX: "3020"
    LOGO_CARD_BRANDING_MAPPING: >
      { VISA:'https://checkout.pagopa.it/assets/creditcard/carta_visa.png',  MASTERCARD:'https://checkout.pagopa.it/assets/creditcard/carta_mc.png', DINERS:'https://checkout.pagopa.it/assets/creditcard/carta_diners.png', MAESTRO:'https://checkout.pagopa.it/assets/creditcard/carta_maestro.png', AMEX:'https://checkout.pagopa.it/assets/creditcard/carta_amex.png', UNKNOWN:'https://checkout.pagopa.it/assets/creditcard/generic.png' }

    SERVER_ERROR_INCLUDE_STACKTRACE: "never"
    ELASTIC_APM_SERVICE_NAME: pagopa-ecommerce-transactions-service
    ELASTIC_APM_APPLICATION_PACKAGES: it.pagopa.ecommerce.transactions
    ELASTIC_APM_SERVER_URL: http://quickstart-apm-http.elastic-system.svc:8200
    ELASTIC_APM_LOG_SENDING: "false"
  envSecret:
    MONGO_PASSWORD: mongo-ecommerce-password
    REDIS_PASSWORD: redis-ecommerce-password
    NODO_CONNECTION_STRING: nodo-connection-string
    NOTIFICATIONS_SERVICE_API_KEY: notifications-service-api-key
    ECOMMERCE_STORAGE_CONNECTION_STRING: ecommerce-storage-connection-string
    PAYMENT_TRANSACTIONS_GATEWAY_API_KEY: payment-transactions-gateway-api-key
    JWT_SECRET: sessions-jwt-secret
    PERSONAL_DATA_VAULT_API_KEY: personal-data-vault-api-key
    ELASTIC_APM_SECRET_TOKEN: elastic-apm-secret-token
    ECOMMERCE_PAYMENT_METHODS_APY_KEY: payment-method-api-key
  keyvault:
    name: "pagopa-p-ecommerce-kv"
    tenantId: "7788edaf-0346-4068-9d79-c868aed15b3d"
  nodeSelector: {}
  tolerations: []
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: node_type
                operator: In
                values:
                  - user
